//
//  FavoriteScreenPresenter.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteScreenPresentationLogic
{
  func presentSomething(response: FavoriteScreen.Something.Response)
}

class FavoriteScreenPresenter: FavoriteScreenPresentationLogic
{
  weak var viewController: FavoriteScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FavoriteScreen.Something.Response)
  {
    let viewModel = FavoriteScreen.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
