//
//  FavoriteScreenInteractor.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteScreenBusinessLogic
{
  func doSomething(request: FavoriteScreen.Something.Request)
}

protocol FavoriteScreenDataStore
{
  //var name: String { get set }
}

class FavoriteScreenInteractor: FavoriteScreenBusinessLogic, FavoriteScreenDataStore
{
  var presenter: FavoriteScreenPresentationLogic?
  var worker: FavoriteScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FavoriteScreen.Something.Request)
  {
    worker = FavoriteScreenWorker()
    worker?.doSomeWork()
    
    let response = FavoriteScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
