//
//  MainScreenWorker.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainScreenWorker {
    func getList(completion: @escaping ((ProductResponse?, NetworkError?))->Void) {
       let url = "https://dummyjson.com/products"
        NetworkManager.shared.fetchData(from: url, method: .get, body: nil) { (result : Result<ProductResponse, NetworkError>)  in
            switch result {
                case .success(let productResponse) :
                    completion((productResponse, nil))
                    break
                case .failure(let error) :
                    completion((nil, error))
                    break
            }
        }
    }
}
