//
//  DetailsScreenRouter.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsScreenRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailsScreenDataPassing
{
  var dataStore: DetailsScreenDataStore? { get }
}

class DetailsScreenRouter: NSObject, DetailsScreenRoutingLogic, DetailsScreenDataPassing
{
  weak var viewController: DetailsScreenViewController?
  var dataStore: DetailsScreenDataStore?
  
}
