//
//  DetailsScreenPresenter.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol DetailsScreenPresentationLogic
{
  func present(response: DetailsScreen.GetData.Response)
  func present(response: DetailsScreen.AddToFav.Response)
  func present(response: DetailsScreen.AddToBasket.Response)
}

class DetailsScreenPresenter: DetailsScreenPresentationLogic
{
    
    weak var viewController: DetailsScreenDisplayLogic?
    
    
    func present(response: DetailsScreen.GetData.Response) {
        
        let product = response.product
        
        if let thumbnailURL = URL(string: product.thumbnail) {
            let imageView = UIImageView()
            imageView.kf.setImage(with: thumbnailURL)
            
            let favImage = response.hasFav ? UIImage(systemName: "heart.fill")! : UIImage(systemName: "heart")!
            
            let viewModel = DetailsScreen.GetData.ViewModel(
                title: product.title,
                price: product.price,
                describe: product.productDescription,
                hasFav: favImage,
                image: imageView.image!
            )
            
            viewController?.display(viewModel: viewModel)
        }
    }
    
    func present(response: DetailsScreen.AddToFav.Response) {
        
        let favImage = response.hasFav ? UIImage(systemName: "heart.fill")! : UIImage(systemName: "heart")!
        let text = response.hasFav ? "Added to Favorite" : "Delete than Favorite"
        
        viewController?.displayFavorite(viewModel: DetailsScreen.AddToFav.ViewModel(hasFav: favImage, resultMessage: text))
    }
    
    func present(response: DetailsScreen.AddToBasket.Response) {
        
    }

}
