//
//  DetailsScreenPresenter.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsScreenPresentationLogic
{
  func presentSomething(response: DetailsScreen.Something.Response)
}

class DetailsScreenPresenter: DetailsScreenPresentationLogic
{
  weak var viewController: DetailsScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DetailsScreen.Something.Response)
  {
    let viewModel = DetailsScreen.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
