//
//  DetailsScreenInteractor.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsScreenBusinessLogic
{
  func doSomething(request: DetailsScreen.Something.Request)
}

protocol DetailsScreenDataStore
{
  //var name: String { get set }
}

class DetailsScreenInteractor: DetailsScreenBusinessLogic, DetailsScreenDataStore
{
  var presenter: DetailsScreenPresentationLogic?
  var worker: DetailsScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DetailsScreen.Something.Request)
  {
    worker = DetailsScreenWorker()
    worker?.doSomeWork()
    
    let response = DetailsScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
