//
//  DetailsScreenModels.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailsScreen
{
  // MARK: Use cases
  
  enum GetData
  {
    struct Request  // Interactor
    {
    }
    struct Response // Presenter
    {
//        let productDetailResponse : ProductResponse
        let product: Product
        let hasFav : Bool
    }
    struct ViewModel // ViewController
    {
        let title : String
        let price : Double
        let describe : String
        let hasFav : UIImage
        let image : UIImage
    }
  }
    
    enum AddToBasket {
        struct Request
        {
            let productID : String
            let itemCount : String
        }
        struct Response
        {
            let isItemAdded : Bool
        }
        struct ViewModel
        {
            let resultMessage: String
        }
    }
    
    
    enum AddToFav {
        struct Request
        {
            let productID : String
            let isFav : Bool
        }
        struct Response
        {
            let hasFav : Bool
        }
        struct ViewModel
        {
            let hasFav : UIImage
            let resultMessage: String
        }
    }
}
