//
//  DetailsScreenInteractor.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsScreenBusinessLogic
{
  func handle(request: DetailsScreen.GetData.Request)
  func handle(request: DetailsScreen.AddToFav.Request)
  func handle(request: DetailsScreen.AddToBasket.Request)
}

protocol DetailsScreenDataStore
{
    var productListResponse: ProductResponse? { get set }
    var selectedItem : Int { get set }
    
    var productionID : Int { get set }
}

class DetailsScreenInteractor: DetailsScreenBusinessLogic, DetailsScreenDataStore
{
    var productionID: Int = 0
    
    var selectedItem: Int = 0
    
    var productListResponse: ProductResponse?
    
    
  var presenter: DetailsScreenPresentationLogic?
  var worker: DetailsScreenWorker?
    
    
//    func handle(request: DetailsScreen.GetData.Request) {
//        guard let response = self.productListResponse else { return }
//        presenter?.present(response: DetailsScreen.GetData.Response(productDetailResponse: response, hasFav: false))
//    }
    
    func handle(request: DetailsScreen.GetData.Request) {
      guard let product = productListResponse?.products[selectedItem] else { return }
        productionID = (productListResponse?.products[selectedItem].id)!
        
        let isFav = FavoriteRepository.shared.isFavorited(productionID: productionID)
        
      presenter?.present(response: DetailsScreen.GetData.Response(product: product, hasFav: isFav))
    }
    
    func handle(request: DetailsScreen.AddToFav.Request) {
        FavoriteRepository.shared.favorite(productionID: productionID, isFav: request.isFav)
        presenter?.present(response: DetailsScreen.AddToFav.Response(hasFav: true))
    }
    
    func handle(request: DetailsScreen.AddToBasket.Request) {
        
    }
    
}
