//
//  BasketScreenInteractor.swift
//  E-Commerce (Clean Swift)
//
//  Created by Vusal Islamzada on 07.03.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasketScreenBusinessLogic
{
  func doSomething(request: BasketScreen.Something.Request)
}

protocol BasketScreenDataStore
{
  //var name: String { get set }
}

class BasketScreenInteractor: BasketScreenBusinessLogic, BasketScreenDataStore
{
  var presenter: BasketScreenPresentationLogic?
  var worker: BasketScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BasketScreen.Something.Request)
  {
    worker = BasketScreenWorker()
    worker?.doSomeWork()
    
    let response = BasketScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
